package com.mixin.demo.ssm.mybatis.mapper;

import com.mixin.demo.ssm.mybatis.UserDomainExample;
import com.mixin.demo.ssm.mybatis.entity.UserDomain;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;

public interface UserDomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Dec 23 13:52:40 CST 2019
     */
    long countByExample(UserDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Dec 23 13:52:40 CST 2019
     */
    int deleteByExample(UserDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Dec 23 13:52:40 CST 2019
     */
    @Insert({
        "insert into t_user (user_name, password, ",
        "phone)",
        "values (#{userName,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{phone,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="userId", before=false, resultType=Integer.class)
    int insert(UserDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Dec 23 13:52:40 CST 2019
     */
    int insertSelective(UserDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Dec 23 13:52:40 CST 2019
     */
    List<UserDomain> selectByExample(UserDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Dec 23 13:52:40 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserDomain record, @Param("example") UserDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Dec 23 13:52:40 CST 2019
     */
    int updateByExample(@Param("record") UserDomain record, @Param("example") UserDomainExample example);
}